export const projectData = [
  {
    id: 1,
    title: "Desoc Website",
    date: "2020",
    client: "Unkown",
    location: "Ghana",
    live: "https://myfavshoe-2.netlify.app/",
    description:
      "A website for the department of graphic design at the University of Education, Winneba",
    status: "online",
    imageUrl: "/images/desoc.jpg",
    category: ["Website", "React", "Interactive"],
    images: [
      "/images/desoc/00.jpg",
      "/images/desoc/01.jpg",
      "/images/desoc/02.jpg",
      "/images/desoc/03.jpg",
      "/images/desoc/04.jpg",
      "/images/desoc/05.jpg",
    ],
  },
  {
    id: 2,
    title: "kaizen",
    date: "2023",
    client: "Michael Badiako",
    location: "Ghana",
    live: "",
    description:
      "A website for the department of graphic design at the University of Education, Winneba",
    status: "notonline",
    imageUrl: "/images/kaizen.jpg",
    category: ["Website", "React", "Interactive"],
    images: [
      "https://res.cloudinary.com/base-data/video/upload/ac_none/v1693359206/images/kaizen/kaizen-design-vid.gif",
      "/images/kaizen/02.jpg",
      "/images/kaizen/03.jpg",
      "/images/kaizen/04.jpg",
      "/images/kaizen/gif.gif",
      "/images/kaizen/last-long.jpg",
    ],
  },
  {
    id: 3,
    title: "Leava",
    date: "2023",
    client: "Michael Badiako",
    location: "Ghana",
    live: "https://leava.framer.website/",
    description:
      "A website for the department of graphic design at the University of Education, Winneba",
    status: "online",
    imageUrl: "/images/leava.jpg",
    category: ["Website", "React", "Interactive"],
    images: [
      "/images/leava/00.jpg",
      "/images/leava/gif.gif",
      "/images/leava/long.jpg",
    ],
  },
];
export const selectedProjectData = [
  {
    id: 1,
    title: "Desoc Website",
    date: "2020",
    client: "Unkown",
    location: "Ghana",
    live: "https://myfavshoe-2.netlify.app/",
    description:
      "A website for the department of graphic design at the University of Education, Winneba",
    status: "online",
    imageUrl: "/images/desoc.jpg",
    category: ["Website", "React", "Interactive"],
    images: [
      "/images/desoc/00.jpg",
      "/images/desoc/01.jpg",
      "/images/desoc/02.jpg",
      "/images/desoc/03.jpg",
      "/images/desoc/04.jpg",
      "/images/desoc/05.jpg",
    ],
  },
  {
    id: 2,
    title: "kaizen",
    date: "2023",
    client: "Michael Badiako",
    location: "Ghana",
    live: "",
    description:
      "A website for the department of graphic design at the University of Education, Winneba",
    status: "notonline",
    imageUrl: "/images/kaizen.jpg",
    category: ["Website", "React", "Interactive"],
    images: [
      "https://res.cloudinary.com/base-data/video/upload/ac_none/v1693359206/images/kaizen/kaizen-design-vid.gif",
      "/images/kaizen/02.jpg",
      "/images/kaizen/03.jpg",
      "/images/kaizen/04.jpg",
      "/images/kaizen/gif.gif",
      "/images/kaizen/last-long.jpg",
    ],
  },
  {
    id: 3,
    title: "Leava",
    date: "2023",
    client: "Michael Badiako",
    location: "Ghana",
    live: "https://leava.framer.website/",
    description:
      "A website for the department of graphic design at the University of Education, Winneba",
    status: "online",
    imageUrl: "/images/leava.jpg",
    category: ["Website", "React", "Interactive"],
    images: [
      "/images/leava/00.jpg",
      "/images/leava/gif.gif",
      "/images/leava/long.jpg",
    ],
  },
];
